# Generated by Django 4.2 on 2023-11-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_order_shipping_address_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/sample.png', upload_to=''),
        ),
    ]
