# Generated by Django 4.2 on 2023-11-18 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 11, 18, 12, 13, 21, 893900, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
